#!/usr/bin/env python3
"""Generate docs/results.md from the manifest and measured results.

Nothing here is hand-maintained. A hand-written list of which cases fail is
wrong within a week; a generated one is wrong only if the generator is.

Each implementation exposes a black-box runner emitting the spec SS 4.3 envelope.
This script invokes each, records what came back, and writes the scorecard and
divergence report. A missing toolchain is reported as `not run`, never silently
omitted (spec SS 4.4).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tomllib
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "conformance" / "manifest.toml"
OUT = ROOT / "docs" / "results.md"

# Black-box runners (spec SS 4.3), and the tool each needs on PATH.
RUNNERS = {
    "python": (["python3", "-c",
                "import sys; sys.path.insert(0, 'impl/python/src'); "
                "from ils_el.cli import main; sys.argv=['ils-el', "
                "'conformance/cases/el/mean-ylt-10k.json']; main()"], "python3"),
    "scala": (["./mill", "run"], "java"),
    "julia": (["julia", "--project=impl/julia", "impl/julia/bin/run.jl"], "julia"),
    "excel": (["python3", "impl/excel/runner.py"], "soffice"),
}

CWD = {"scala": ROOT / "impl" / "scala"}


def invoke(impl: str) -> tuple[str, list[dict]]:
    cmd, needs = RUNNERS[impl]
    if shutil.which(needs) is None:
        return "not run", []
    try:
        proc = subprocess.run(
            cmd, cwd=CWD.get(impl, ROOT), capture_output=True, text=True,
            timeout=900, env={**__import__("os").environ,
                              "CONFORMANCE_ROOT": str(ROOT)},
        )
    except subprocess.TimeoutExpired:
        return "timeout", []
    except (FileNotFoundError, PermissionError):
        # Build tool not bootstrapped in this environment.
        return "not run", []
    if proc.returncode != 0:
        return "error", []

    rows = parse_envelope(proc.stdout)
    return ("ok", rows) if rows is not None else ("error", [])


def parse_envelope(payload: str) -> list[dict] | None:
    """Parse a runner's stdout into envelope rows, or None if it is not JSON.

    Tolerant of leading noise: a build tool or a language runtime may print a
    banner, a precompilation notice or a progress ticker onto the same stream
    the envelope is written to. Returns a list even for a single object, which
    spec SS 4.3 permits.
    """
    payload = payload.strip()
    start = min((i for i in (payload.find("["), payload.find("{")) if i >= 0), default=-1)
    if start < 0:
        return None
    try:
        data = json.loads(payload[start:])
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, list) else [data]


def from_dir(d: Path) -> tuple[dict[str, str], dict[str, dict[str, dict]]]:
    """CI path: each implementation job uploads its envelope as an artifact.

    Preferred over invoking runners here, because it keeps every toolchain in
    its own job and lets a single implementation fail without taking the
    scorecard down with it.
    """
    status: dict[str, str] = {}
    measured: dict[str, dict[str, dict]] = {}
    for impl in ("python", "scala", "julia", "excel"):
        f = d / f"results-{impl}.json"
        if not f.exists():
            status[impl], measured[impl] = "not run", {}
            continue
        rows = parse_envelope(f.read_text(encoding="utf-8"))
        if rows is None:
            status[impl], measured[impl] = "error", {}
            continue
        status[impl] = "ok"
        measured[impl] = {r["case"]: r for r in rows if "value" in r}
    return status, measured


def main() -> int:
    ap = argparse.ArgumentParser(prog="scorecard")
    ap.add_argument("--results-dir", type=Path,
                    help="read results-<impl>.json instead of invoking runners")
    args = ap.parse_args()

    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    cases = {
        c["id"]: c
        for c in (json.loads(p.read_text(encoding="utf-8"))
                  for p in sorted((ROOT / "conformance" / "cases").rglob("*.json")))
    }

    if args.results_dir:
        status, measured = from_dir(args.results_dir)
    else:
        measured, status = {}, {}
        for impl in manifest["implementations"]:
            state, results = invoke(impl)
            status[impl] = state
            measured[impl] = {r["case"]: r for r in results}

    lines = [
        "# Results",
        "",
        "!!! note",
        "    Generated by `tools/scorecard.py`. Do not edit.",
        "",
        f"Spec version **{manifest['spec_version']}** · "
        f"generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC",
        "",
        "## Scorecard",
        "",
        "| implementation | tier | targets | engine | cases | result |",
        "|---|---|---|---|---|---|",
    ]

    for impl, meta in manifest["implementations"].items():
        decl = manifest.get("cases", {})
        passed = failed = unsupported = 0
        for cid, case in cases.items():
            entry = decl.get(cid, {})
            if impl in entry.get("unsupported", {}):
                unsupported += 1
                continue
            r = measured[impl].get(cid)
            if r is None:
                continue
            expected = float(Decimal(case["expected"]["exact_decimal"]))
            err = abs(float(r["value"]) - expected) / abs(expected)
            if err <= case["tolerance"]["rel"]:
                passed += 1
            else:
                failed += 1

        total = len(cases) - unsupported
        verdict = {
            "not run": "toolchain unavailable",
            "timeout": "**timeout**",
            "error": "**runner error**",
        }.get(status[impl], "pass" if failed == 0 and passed == total else f"**{failed} failed**")
        lines.append(
            f"| `{impl}` | {meta['tier']} | {meta['targets']} | "
            f"{meta.get('engine', '—')} | {passed}/{total}"
            + (f" (+{unsupported} unsupported)" if unsupported else "")
            + f" | {verdict} |"
        )

    lines += ["", "## Per-case detail", ""]
    for cid, case in cases.items():
        lines += [
            f"### `{cid}`", "",
            f"Spec § {case['spec']} · since {case['since']} · "
            f"relative tolerance {case['tolerance']['rel']:.0e}", "",
            f"> {case['rationale']}", "",
            f"Exact result: `{case['expected']['exact_decimal']}`", "",
            "| implementation | value | relative error |", "|---|---|---|",
        ]
        expected = float(Decimal(case["expected"]["exact_decimal"]))
        for impl in manifest["implementations"]:
            r = measured[impl].get(cid)
            if r is None:
                lines.append(f"| `{impl}` | — | not run |")
                continue
            actual = float(r["value"])
            err = abs(actual - expected) / abs(expected)
            mark = "" if err <= case["tolerance"]["rel"] else " ⚠"
            shown = "exact" if err == 0.0 else f"{err:.1e}"
            lines.append(f"| `{impl}` | `{actual!r}` | {shown}{mark} |")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    # spec/spec.md is canonical; docs/ gets a copy so mkdocs has one tree.
    # newline is pinned: the default translates to CRLF on Windows, which would
    # make the copy differ from its source on every line.
    (ROOT / "docs" / "spec.md").write_text(
        (ROOT / "spec" / "spec.md").read_text(encoding="utf-8"),
        encoding="utf-8", newline="\n",
    )
    print(f"wrote {OUT.relative_to(ROOT)}")
    for impl, state in status.items():
        print(f"  {impl:8} {state}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
